### ISSUE TITLE
Set up test deployment on our test k8s cluster

### ISSUE THREAD

**Issue by amoeba** [DataONEorg/slinky#27] opened 2021-03-26 00:10 UTC
As of https://github.com/DataONEorg/slinky/issues/3, @ThomasThelen has gotten Slinky running under minikube so the next thing to work on is to get a real deployment under k8s going so we can test all the odds and ends of getting that done (ie Docker Hub, ingress, etc).

What would be ideal would be hooking things up enough that I can, as a developer, make changes to services like the worker or scheduler, and see my changes reflected in the test cluster relatively quickly.

**Comment by ThomasThelen** [comment] 2021-04-30 19:44
I think one of the last things we'll need to do is switch the volume driver over to ceph. I'll be providing an estimate for the amount of space our volumes will need. Persistent volumes are on the _cluster_ level, which the slinky account doesn't have access to (for security reasons). Giving an estimate of the space should give administrators a good estimate of how much space to allocate for PV's on the cluster which the PVC's can then fill.

More information on ceph can be found in the NCEAS _Computing_ repository.

**Comment by gothub** [comment] 2021-05-01 20:08
@ThomasThelen @amoeba  A PV is setup on the k8s dev cluster that slinky can use. The PV was created with the admin context.
Using the slinky 'kubeconfig' that is in Keybase, here is an example (run on my laptop) of creating a slinky PVC that uses the PV
```
avatar:slinky slaughter$ kubectl create -f pvc.yaml
persistentvolumeclaim/slinky-pvc created
avatar:slinky slaughter$ kubectl get pvc
NAME         STATUS   VOLUME    CAPACITY   ACCESS MODES   STORAGECLASS   AGE
slinky-pvc   Bound    nfs2-pv   50Gi       RWX                           6s
avatar:slinky slaughter$ more pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: slinky-pvc
  namespace: slinky
spec:
  accessModes:
  - ReadWriteMany
  resources:
     requests:
       storage: 50Gi
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: nfs2-pv
```

The PV and PVC use NFS, which is temporary until Ceph can be setup, but this should be sufficient for testing.
Please let me know if you encounter any problems with the PV or PVC.

**Comment by amoeba** [comment] 2021-05-05 00:43
Thanks @gothub! I talked with @ThomasThelen and he's going to test it out soon.

**Comment by ThomasThelen** [comment] 2021-06-29 16:20
The core services are deployed and stable; once we determine precisely how we want to [expose virtuoso](https://github.com/DataONEorg/api-entrypoint/issues/9) we can close this issue.

**Comment by ThomasThelen** [comment] 2021-07-09 22:15
Linked to #41 because after it's accepted, we'll have a fully protected dev deployment that we can test on. It's also been confirmed that the graph has been populating using the geolink convention.

**Closed as completed** 2021-07-13 22:05 UTC
Labels: semantics
